### ISSUE TITLE
Great tool, could we add ClickHouse support?

### ISSUE THREAD

**Issue by Slach** [plmercereau/chat-dbt#19]
Thank you so much for your efforts!

**Comment by plmercereau** [comment]
That shouldn't be too difficult, I'll have a look soon

**Comment by plmercereau** [comment]
Hello @Slach, it is now possible to use the tool with ClickHouse, please use the [latest version of the package](https://github.com/plmercereau/chat-dbt/releases/tag/v0.5.0).

You only need to set the connection string like this:
```sh
chat-dbt --database clickhouse://username:password@server
```

If you need to use `https`, pass on the `secure=true` option:
```sh
chat-dbt --database clickhouse://username:password@server?secure=true
```

I've made some tests manually, and it seems to work fine. Don't hesitate to open an issue if you find something missing.
Enjoy
